### ISSUE TITLE
Add Time of Completion to notification

### ISSUE THREAD

**Issue by emmaisadev** [tigattack/VeeamDiscordNotifications#12]
When many notifications are sent at once, Discord hides the time of messages.

As  a user, I would like to be able to see the time at which my Job completed and possibly started, in order to give more context to the time taken metric.

DoD:
Add "Time Completed" to Discord Notification
Stretch:
Add "Time Started" to Discord notification

**Comment by tigattack** [comment]
Resolved in 8adcc3860c5030d33e041d460e20e77c6bafb779. Will be out in the next release.
